showcase_homepage:
    path: /
    defaults: { _controller: ShowcaseBundle:Default:index }

showcase_service:
    path: /service/{slug}
    defaults: { _controller: ShowcaseBundle:Default:service }

showcase_order:
    path: /order/{slug}
    defaults: { _controller: ShowcaseBundle:Default:order }