admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

sonata_admin_calendar:
    path:  /calendar
    host: admin.%base_host%
    defaults: { _controller: AdminBundle:Calendar:index }

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    host: admin.%base_host%

showcase:
    resource: "@ShowcaseBundle/Resources/config/routing.yml"
    host: showcase.%base_host%

app:
    resource: "@AppBundle/Controller/"
    type:     annotation