admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

sonata_admin_calendar:
    path:  /calendar/{timestamp}
    host: admin.%base_host%
    defaults: { _controller: AdminBundle:Calendar:index, timestamp: null}

sonata_admin_calendar_delete:
    path:  /calendar/delete/{id}
    host: admin.%base_host%
    defaults: { _controller: AdminBundle:Calendar:delete }
    methods: [POST]

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    host: admin.%base_host%

showcase:
    resource: "@ShowcaseBundle/Resources/config/routing.yml"
    host: showcase.%base_host%

app:
    resource: "@AppBundle/Controller/"
    type:     annotation