security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ACCESS_ADMINPANEL]
        ROLE_SECRETARY: [ROLE_ACCESS_ADMINPANEL]

#        ROLE_ADMIN_SERVICE_CATEGORY:
#            - ROLE_ADMIN_SERVICE_CATEGORY_ALL
#
#        ROLE_ADMIN_SERVICE:
#            - ROLE_ADMIN_SERVICE_ALL
#
#        ROLE_USER:
#            - ROLE_ADMIN_SERVICE_CATEGORY
#            - ROLE_ADMIN_SERVICE

#        ROLE_ADMIN: ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN

#    access_decision_manager:
#        strategy: unanimous

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            entity:
                class: AppBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            guard:
                authenticators:
                    - app.security.login_form_authenticator

            logout:
                path: /logout

    access_control:
        - { host: ^admin\., path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: ^admin\., path: ^/, roles: ROLE_ACCESS_ADMINPANEL }