# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    AppBundle.db.table_prefix: law_

services:
    appbundle.tblprefix_subscriber:
        class: AppBundle\Subscriber\TablePrefixSubscriber
        arguments: [%AppBundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
