# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    appbundle.db.table_prefix: law_

services:
    # сервисы
    app.file_uploader:
        class: AppBundle\Services\FileUploader
        arguments: ['%documents_upload_directory%']

    # Обработчки событий
    appbundle.tblprefix_subscriber:
        class: AppBundle\Subscriber\TablePrefixSubscriber
        arguments: ['%appbundle.db.table_prefix%']
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.event.order_form_submitted:
        class: AppBundle\Subscriber\OrderFormSubmittedSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    app.doctrine_file_upload_listener:
        class: AppBundle\Subscriber\OrderFileUploadSubscriber
        arguments: ['@app.file_uploader']
        tags:
            - { name: doctrine.event_subscriber }