# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    appbundle.db.table_prefix: law_

services:
    # сервисы
    app.file_uploader:
        class: AppBundle\Services\FileUploader
        arguments: ['%documents_upload_directory%', '%documents_upload_directory_relative_from_web%']

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        arguments: ['@form.factory', '@doctrine.orm.default_entity_manager', '@security.password_encoder', '@router']

    # SonataAdminBundle
#     sonata.block.service.dashboard:
#       class: AdminBundle\Block\DashboardBlockService
#       arguments: ['sonata.block.service.dashboard', '@templating']
#       calls:
#         - [setStatisticService, ['@app.statistics']]
#       tags:
#           - { name: sonata.block }
    admin.service_category:
        class: AdminBundle\Admin\ServiceCategoryAdmin
        arguments: [~, AppBundle\Entity\ServiceCategory, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Категории"
              group: "Витрина услуг"

    admin.service:
        class: AdminBundle\Admin\ServiceAdmin
        arguments: [~, AppBundle\Entity\Service, ~, '@app.file_uploader', '@assets.packages']
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Услуги"
              group: "Витрина услуг"

    admin.service_modification:
        class: AdminBundle\Admin\ServiceModificationAdmin
        arguments: [~, AppBundle\Entity\ServiceModification, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Модификации услуг"
              group: "Витрина услуг"

    admin.users:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~, '@app.file_uploader', '@assets.packages']
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Сотрудники"
              group: "Пользователи"

    # Обработчки событий
    appbundle.tblprefix_subscriber:
        class: AppBundle\Subscriber\TablePrefixSubscriber
        arguments: ['%appbundle.db.table_prefix%']
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.event.user_password_changed:
        class: AppBundle\Subscriber\UserPasswordChangedSubscriber
        arguments: ['@mailer', '@templating', '%email_from%']
        tags:
            - { name: kernel.event_subscriber }

    app.doctrine_file_upload_listener:
        class: AppBundle\Subscriber\OrderFileUploadSubscriber
        arguments: ['@app.file_uploader']
        tags:
            - { name: doctrine.event_subscriber }