# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    appbundle.db.table_prefix: law_

services:
    # сервисы
    app.file_uploader:
        class: AppBundle\Services\FileUploader
        arguments: ['%documents_upload_directory%', '%documents_upload_directory_relative_from_web%']

    app.file_downloader:
        class: AppBundle\Services\FileDownloader
        autowire: true

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        arguments: ['@form.factory', '@doctrine.orm.default_entity_manager', '@security.password_encoder', '@router']

    # Service Layer
    app.sl.order:
       class: AppBundle\ServiceLayer\OrderService
       arguments: ["@doctrine.orm.entity_manager", "@app.file_downloader", "@app.file_uploader", "@service_container"]

    app.sl.schedule:
       class: AppBundle\ServiceLayer\ScheduleEventsService
       arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    # SonataAdminBundle

#     sonata.block.service.dashboard:
#       class: AdminBundle\Block\DashboardBlockService
#       arguments: ['sonata.block.service.dashboard', '@templating']
#       calls:
#         - [setStatisticService, ['@app.statistics']]
#       tags:
#           - { name: sonata.block }
    admin.service_category:
        class: AdminBundle\Admin\ServiceCategoryAdmin
        arguments: [~, AppBundle\Entity\ServiceCategory, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Категории"
              group: "Витрина услуг"

    admin.finance:
        class: AdminBundle\Admin\FinanceAdmin
        arguments: [~, AppBundle\Entity\Finance, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Финансы"
              group: "Дела и пользователи"

    admin.service:
        class: AdminBundle\Admin\ServiceAdmin
        arguments: [~, AppBundle\Entity\Service, ~, '@app.file_uploader', '@assets.packages']
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Услуги"
              group: "Витрина услуг"

    admin.service_modification:
        class: AdminBundle\Admin\ServiceModificationAdmin
        arguments: [~, AppBundle\Entity\ServiceModification, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Модификации услуг"
              group: "Витрина услуг"

    admin.users.clients:
        class: AdminBundle\Admin\UserClientAdmin
        arguments: [~, AppBundle\Entity\User, ~, '@app.file_uploader', '@assets.packages']
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Клиенты"
              group: "Дела и пользователи"

    admin.users:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~, '@app.file_uploader', '@assets.packages']
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Сотрудники"
              group: "Дела и пользователи"

    admin.orders:
        class: AdminBundle\Admin\OrderAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Дела"
              group: "Дела и пользователи"
        arguments:
            - null
            - AppBundle\Entity\Order
            - AdminBundle:OrderCRUD

    admin.orders.lawyer:
        class: AdminBundle\Admin\OrderLawyerAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Дела"
              group: "Дела и пользователи"
        arguments:
            - null
            - AppBundle\Entity\Order
            - AdminBundle:OrderCRUD

    admin.orders.client:
        class: AdminBundle\Admin\OrderClientAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Дела"
              group: "Дела и пользователи"
        arguments:
            - null
            - AppBundle\Entity\Order
            - AdminBundle:OrderCRUD

    # Обработчки событий
    appbundle.tblprefix_subscriber:
        class: AppBundle\Subscriber\TablePrefixSubscriber
        arguments: ['%appbundle.db.table_prefix%']
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.event.user_password_changed:
        class: AppBundle\Subscriber\UserPasswordChangedSubscriber
        arguments: ['@mailer', '@templating', '%email_from%']
        tags:
            - { name: kernel.event_subscriber }

    app.event.order_status_changed:
        class: AppBundle\Subscriber\OrderStatusChangedSubscriber
        arguments: ['@mailer', '@templating', '%email_from%']
        tags:
            - { name: kernel.event_subscriber }

    app.event.order_file_uploaded:
        class: AppBundle\Listener\OrderFileUploadedListener
        arguments: ["@app.sl.order", "@router", "@service_container"]
        tags:
            - { name: kernel.event_listener, event: 'app.event.order_file_uploaded', method: 'onOrderFileUploaded'}

    app.doctrine_file_upload_listener:
        class: AppBundle\Subscriber\OrderFileUploadSubscriber
        arguments: ['@app.file_uploader']
        tags:
            - { name: doctrine.event_subscriber }

    app.event.order_update_activity:
        class: AppBundle\Subscriber\OrderRecentActivitySubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

    order_listener:
        class: AppBundle\Listener\OrderListener
        arguments: ['@mailer', '@templating', '%email_from%']
        tags:
            - { name: doctrine.orm.entity_listener }

    app.http_client:
        class: GuzzleHttp\Client

    app.contract_creator:
        class: AppBundle\Services\ContractCreator
        arguments: ['@app.http_client', '%doc_ssn%', '%doc_tpl_path%', '%doc_service_url%']