-- MySQL Script generated by MySQL Workbench
-- Вт. 28 февр. 2017 18:12:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`law_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`law_users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(180) NOT NULL,
  `second_name` VARCHAR(180) NOT NULL,
  `middle_name` VARCHAR(180) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `other_contacts` TEXT NULL,
  `confirmation_token` VARCHAR(180) NULL,
  `roles` LONGTEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `confirmation_token_UNIQUE` (`confirmation_token` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`law_orders_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`law_orders_types` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(180) NOT NULL,
  `short_description` TEXT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `image_url` VARCHAR(512) NULL,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`law_orders_modifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`law_orders_modifications` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_type_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` TEXT NOT NULL,
  `time_limit` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_orders_modifications_1_idx` (`order_type_id` ASC),
  CONSTRAINT `fk_law_orders_modifications_1`
    FOREIGN KEY (`order_type_id`)
    REFERENCES `mydb`.`law_orders_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`law_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`law_orders` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_modification_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'time_limit - словесно. Например, \"5 дней\"',
  `status` TINYINT(4) UNSIGNED NOT NULL COMMENT '0 - В работе\n1 - Новая\n2 - Завершенная',
  `title` VARCHAR(155) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `is_payment_received` TINYINT(1) NULL,
  `created_at` DATETIME NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `orders_status_idx` (`status` ASC),
  INDEX `fk_law_orders_1_idx` (`user_id` ASC),
  INDEX `fk_law_orders_2_idx` (`order_modification_id` ASC),
  CONSTRAINT `fk_law_orders_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`law_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_law_orders_2`
    FOREIGN KEY (`order_modification_id`)
    REFERENCES `mydb`.`law_orders_modifications` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`law_orders_actions_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`law_orders_actions_history` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `action_type` TINYINT(4) NOT NULL,
  `additional_information` TEXT NULL,
  `created_at` DATETIME NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_orders_actions_history_1_idx` (`order_id` ASC),
  CONSTRAINT `fk_law_orders_actions_history_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`law_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`law_orders_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`law_orders_files` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `file_path` VARCHAR(512) NOT NULL,
  `type` TINYINT(4) NULL,
  `created_at` DATETIME NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_orders_files_1_idx` (`order_id` ASC),
  CONSTRAINT `fk_law_orders_files_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`law_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`law_orders_chat_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`law_orders_chat_messages` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `is_from_lawyer` TINYINT(1) NOT NULL DEFAULT 0,
  `text` MEDIUMTEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_order_chat_messages_1_idx` (`order_id` ASC),
  CONSTRAINT `fk_law_order_chat_messages_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`law_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`law_schedule_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`law_schedule_events` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `type` TINYINT(4) NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `description` TEXT NULL,
  `date` DATETIME NOT NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_schedule_events_1_idx` (`user_id` ASC),
  INDEX `shedule_events_status_idx` (`status` ASC),
  CONSTRAINT `fk_law_schedule_events_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`law_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`law_private_orders_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`law_private_orders_comments` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `is_from_lawyer` TINYINT(1) NOT NULL DEFAULT 1,
  `text` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_private_order_comments_1_idx` (`order_id` ASC),
  CONSTRAINT `fk_law_private_order_comments_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`law_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
