-- MySQL Script generated by MySQL Workbench
-- Пт. 10 марта 2017 14:55:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `law_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(180) NOT NULL,
  `second_name` VARCHAR(180) NOT NULL,
  `middle_name` VARCHAR(180) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `other_contacts` TEXT NULL,
  `email_confirmation_token` VARCHAR(180) NULL,
  `phone_confirmation_token` VARCHAR(5) NULL,
  `role` VARCHAR(180) NOT NULL,
  `avatar_url` VARCHAR(512) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `confirmation_token_UNIQUE` (`email_confirmation_token` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_confirmation_token_UNIQUE` (`phone_confirmation_token` ASC))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `law_services_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_services_categories` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `law_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_services` (
  `id` INT(10) UNSIGNED NOT NULL,
  `service_category_id` INT(10) UNSIGNED NULL,
  `title` VARCHAR(180) NOT NULL,
  `slug` VARCHAR(128) NOT NULL,
  `short_description` TEXT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `image_url` VARCHAR(512) NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_services_1_idx` (`service_category_id` ASC),
  CONSTRAINT `fk_law_services_1`
  FOREIGN KEY (`service_category_id`)
  REFERENCES `law_services_categories` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `law_services_modifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_services_modifications` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` TEXT NOT NULL,
  `time_limit` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_orders_modifications_1_idx` (`service_id` ASC),
  CONSTRAINT `fk_law_orders_modifications_1`
  FOREIGN KEY (`service_id`)
  REFERENCES `law_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `law_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_orders` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_modification_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'time_limit - словесно. Например, \"5 дней\"',
  `lawyer_id` INT(10) UNSIGNED NOT NULL,
  `status` TINYINT(4) UNSIGNED NOT NULL COMMENT '0 - В работе\n1 - Новая\n2 - Выполнена\n3 - Отменена\n4 - Просрочена\n5 - ожидает оплаты',
  `title` VARCHAR(155) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `orders_status_idx` (`status` ASC),
  INDEX `fk_law_orders_1_idx` (`user_id` ASC),
  INDEX `fk_law_orders_2_idx` (`service_modification_id` ASC),
  INDEX `fk_law_orders_3_idx` (`lawyer_id` ASC),
  CONSTRAINT `fk_law_orders_1`
  FOREIGN KEY (`user_id`)
  REFERENCES `law_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_law_orders_2`
  FOREIGN KEY (`service_modification_id`)
  REFERENCES `law_services_modifications` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_law_orders_3`
  FOREIGN KEY (`lawyer_id`)
  REFERENCES `law_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `law_orders_actions_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_orders_actions_history` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `action_type` TINYINT(4) NOT NULL,
  `additional_information` TEXT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_orders_actions_history_1_idx` (`order_id` ASC),
  CONSTRAINT `fk_law_orders_actions_history_1`
  FOREIGN KEY (`order_id`)
  REFERENCES `law_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `law_orders_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_orders_files` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `file_path` VARCHAR(512) NOT NULL,
  `type` TINYINT(4) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_orders_files_1_idx` (`order_id` ASC),
  CONSTRAINT `fk_law_orders_files_1`
  FOREIGN KEY (`order_id`)
  REFERENCES `law_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `law_orders_chat_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_orders_chat_messages` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `user_from` INT(10) UNSIGNED NOT NULL,
  `user_to` INT(10) UNSIGNED NULL,
  `text` MEDIUMTEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_order_chat_messages_1_idx` (`order_id` ASC),
  INDEX `fk_law_orders_chat_messages_1_idx` (`user_from` ASC),
  INDEX `fk_law_orders_chat_messages_2_idx` (`user_to` ASC),
  CONSTRAINT `fk_law_order_chat_messages_1`
  FOREIGN KEY (`order_id`)
  REFERENCES `law_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_law_orders_chat_messages_1`
  FOREIGN KEY (`user_from`)
  REFERENCES `law_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_law_orders_chat_messages_2`
  FOREIGN KEY (`user_to`)
  REFERENCES `law_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `law_schedule_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_schedule_events` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `type` TINYINT(4) NOT NULL,
  `status` TINYINT(4) NOT NULL COMMENT '0 - новая\n1 - выполнена\n2 - отменена\n3 - просрочена',
  `description` TEXT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_schedule_events_1_idx` (`user_id` ASC),
  INDEX `shedule_events_status_idx` (`status` ASC),
  CONSTRAINT `fk_law_schedule_events_1`
  FOREIGN KEY (`user_id`)
  REFERENCES `law_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `law_private_orders_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_private_orders_comments` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `is_from_lawyer` TINYINT(1) NOT NULL DEFAULT 1,
  `text` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_private_order_comments_1_idx` (`order_id` ASC),
  CONSTRAINT `fk_law_private_order_comments_1`
  FOREIGN KEY (`order_id`)
  REFERENCES `law_orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `law_orders_payment_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `law_orders_payment_info` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_type` TINYINT(4) NULL,
  `is_moneyback` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 - возвра денежных средств клиенту\n0 - поступление денежных средст ОТ клиента',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_law_orders_payment_info_1_idx` (`order_id` ASC),
  CONSTRAINT `fk_law_orders_payment_info_1`
  FOREIGN KEY (`order_id`)
  REFERENCES `law_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
